name: Builder

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Lockup
    runs-on: ubuntu-latest
    steps:
    - name: Check out code base
      uses: actions/checkout@v1

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: 15

    - name: "Permission to gradle File"
      run: chmod +x gradlew

    - name: Build with Gradle
      run: |
        ./gradlew assemble
        ./gradlew assembleDebug
        ./gradlew assembleOss
        ./gradlew assembleRelease

    - name: List files
      run: |
        ls -R .

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: lockup
        path: ./app/build/*
